### ISSUE TITLE
Why SDK Readme not show MacOS tool chain

### ISSUE THREAD

**Issue by PMLSTaisen** [bouffalolab/bl_mcu_sdk#103] opened 2023-03-01 02:23 UTC
I do find the MacOS tool chain from [https://dev.bouffalolab.com/download](https://dev.bouffalolab.com/download) , but why Readme only list tool chain for Windows and Linux? Person like me take very long time to find our there is MacOS tool chain ready. Could you add into github and make link easy for everyone?

**Comment by sakumisu** [comment] 2023-03-01 02:24
Build by yourself

**Comment by sakumisu** [comment] 2023-03-01 02:25
T-head official does not provide mac toolchain.

**Comment by PMLSTaisen** [comment] 2023-03-01 02:31
Any instruction to build under MacOS for toolchain? Under the [https://dev.bouffalolab.com/download](https://dev.bouffalolab.com/download) this webpage, why it list a MacOS toolchain? `toolchain_riscv_sifive_macos` is different from T-Head version Windows?

**Comment by sakumisu** [comment] 2023-03-01 02:33
It is different.

**Comment by sakumisu** [comment] 2023-03-01 02:33
Follow this: https://github.com/p4ddy1/pine_ox64/blob/main/build_toolchain_macos.md

**Comment by brainstorm** [comment] 2023-03-04 10:36
This issue seems to be a duplicate of my own on https://github.com/bouffalolab/bl_mcu_sdk/issues/83.

**Closed** 2023-03-04 15:26 UTC
